version: "3.9"

services:
  torrent-stream:
    container_name: torrent_stream_server
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3050
      OPENSUBTITLES_API_KEY: ${OPENSUBTITLES_API_KEY}
    ports:
      - "3050:3050"
    networks:
      - stream-net
    volumes:
      - torrent-data:/tmp/webtorrent/tmp
    deploy:
      resources:
        limits:
          memory: 1G

networks:
  stream-net:
    driver: bridge

volumes:
  torrent-data:
    driver: local
